# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

project_name: vectree

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=1
      - >-
        {{- if eq .Os "darwin" }}SDKROOT={{ .Env.SDK_PATH }}{{- end }}
      - >-
        {{- if eq .Os "darwin" }}MACOSX_DEPLOYMENT_TARGET=11.0{{- end }}
      - >-
        {{- if eq .Os "darwin" }}
          {{- if eq .Arch "amd64" }}CC=zig cc -target x86_64-macos -isysroot {{ .Env.SDK_PATH }}{{- end }}
          {{- if eq .Arch "arm64" }}CC=zig cc -target aarch64-macos -isysroot {{ .Env.SDK_PATH }}{{- end }}
        {{- else if eq .Os "linux" }}
          {{- if eq .Arch "amd64" }}CC=zig cc -target x86_64-linux-musl -lc{{- end }}
          {{- if eq .Arch "arm64" }}CC=zig cc -target aarch64-linux-musl -lc{{- end }}
        {{- end }}
      - >-
        {{- if eq .Os "darwin" }}
          {{- if eq .Arch "amd64" }}CXX=zig c++ -target x86_64-macos -isysroot {{ .Env.SDK_PATH }}{{- end }}
          {{- if eq .Arch "arm64" }}CXX=zig c++ -target aarch64-macos -isysroot {{ .Env.SDK_PATH }}{{- end }}
        {{- else if eq .Os "linux" }}
          {{- if eq .Arch "amd64" }}CXX=zig c++ -target x86_64-linux-musl -lc{{- end }}
          {{- if eq .Arch "arm64" }}CXX=zig c++ -target aarch64-linux-musl -lc{{- end }}
        {{- end }}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
    flags:
      - -trimpath

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [Christoph Niederer](https://github.com/niedch).

