all: false
filename: '{{.Mock}}{{.InterfaceName}}.go'
packages:
  github.com/niedch/tree-rag/internal/ai:
    config:
      all: true
  github.com/niedch/tree-rag/internal/store:
    config:
      all: true
  github.com/niedch/tree-rag/internal/stages:
    config:
      all: true
  github.com/niedch/tree-rag/internal/datastore:
    config:
      all: true
