[database]
connection_string = "kownledgebase.db?cache=shared&mode=rw"

[pipeline]
connectall_path = "../connectall"
embedder_batch_size = 64
embedder_workers = 8
store_batch_size = 8
docu_loader_workers = 10

[ai]
embedding_model = "embedding-001"

[retrieval]
similarity_results = 5
