[sources.eddi-docs]
type = "http"
url = "https://techdocs.broadcom.com/us/en/ca-enterprise-software/valueops/connectall/4-0/jcr:content.toc.html"

# [sources.gemini-docs]
# type = "http"
# url = "https://ai.google.dev/gemini-api/docs"
#
# [sources.markdown]
# type = "markdown"
# location = "../test"


[database]
connection_string = "kownledgebase.db?cache=shared&mode=rw"

[pipeline]
embedder_batch_size = 64
embedder_workers = 8
store_batch_size = 64
docu_loader_workers = 10

[ai]
embedding_model = "text-embedding-004"

[retrieval]
similarity_results = 3
