[tools]
go = "1.26.1"
"go:github.com/spf13/cobra-cli" = "1.3.0"
"go:github.com/vektra/mockery/v3" = "3.7.0"

#######################################################
######################## Tasks ########################
#######################################################

[tasks.generate]
description = "Generate Mocks"
run = "mockery"

[tasks.test]
depends = ["generate"]
description = "Tests the Pipeline"
run = "go test ./... -v"

[tasks.build]
depends = ["test"]
description = "Builds project"
run = "go build -o target/tree-rag ."

[tasks.dev]
description = "Run dev build"
run = "go run ."

[tasks.update-deps]
description = "Updates all dependencies"
run = """
go get -u
go mod tidy
"""

[tasks.benchmark]
description = "Runs benchmark & open profiler"
run = """
mkdir -p target/
go test -bench=. -benchmem -memprofile target/profile.out ./internal/pipeline
go tool pprof -http=:8080 target/profile.out
"""

[tasks.docker]
description = "Build docker image"
run = """
	docker build
		--build-arg GEMINI_API_KEY=${GEMINI_API_KEY}
		-t connectall-doc-rag .
"""

