// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package datastore

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockQuerier creates a new instance of MockQuerier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQuerier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQuerier {
	mock := &MockQuerier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQuerier is an autogenerated mock type for the Querier type
type MockQuerier struct {
	mock.Mock
}

type MockQuerier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQuerier) EXPECT() *MockQuerier_Expecter {
	return &MockQuerier_Expecter{mock: &_m.Mock}
}

// CountDocumentEmbeddings provides a mock function for the type MockQuerier
func (_mock *MockQuerier) CountDocumentEmbeddings(ctx context.Context) (int, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CountDocumentEmbeddings")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_CountDocumentEmbeddings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountDocumentEmbeddings'
type MockQuerier_CountDocumentEmbeddings_Call struct {
	*mock.Call
}

// CountDocumentEmbeddings is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockQuerier_Expecter) CountDocumentEmbeddings(ctx interface{}) *MockQuerier_CountDocumentEmbeddings_Call {
	return &MockQuerier_CountDocumentEmbeddings_Call{Call: _e.mock.On("CountDocumentEmbeddings", ctx)}
}

func (_c *MockQuerier_CountDocumentEmbeddings_Call) Run(run func(ctx context.Context)) *MockQuerier_CountDocumentEmbeddings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockQuerier_CountDocumentEmbeddings_Call) Return(n int, err error) *MockQuerier_CountDocumentEmbeddings_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockQuerier_CountDocumentEmbeddings_Call) RunAndReturn(run func(ctx context.Context) (int, error)) *MockQuerier_CountDocumentEmbeddings_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteDocument provides a mock function for the type MockQuerier
func (_mock *MockQuerier) DeleteDocument(ctx context.Context, id int) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDocument")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQuerier_DeleteDocument_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteDocument'
type MockQuerier_DeleteDocument_Call struct {
	*mock.Call
}

// DeleteDocument is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockQuerier_Expecter) DeleteDocument(ctx interface{}, id interface{}) *MockQuerier_DeleteDocument_Call {
	return &MockQuerier_DeleteDocument_Call{Call: _e.mock.On("DeleteDocument", ctx, id)}
}

func (_c *MockQuerier_DeleteDocument_Call) Run(run func(ctx context.Context, id int)) *MockQuerier_DeleteDocument_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_DeleteDocument_Call) Return(err error) *MockQuerier_DeleteDocument_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQuerier_DeleteDocument_Call) RunAndReturn(run func(ctx context.Context, id int) error) *MockQuerier_DeleteDocument_Call {
	_c.Call.Return(run)
	return _c
}

// GetDocument provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetDocument(ctx context.Context, id int) (*Document, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetDocument")
	}

	var r0 *Document
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*Document, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *Document); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Document)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetDocument_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDocument'
type MockQuerier_GetDocument_Call struct {
	*mock.Call
}

// GetDocument is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockQuerier_Expecter) GetDocument(ctx interface{}, id interface{}) *MockQuerier_GetDocument_Call {
	return &MockQuerier_GetDocument_Call{Call: _e.mock.On("GetDocument", ctx, id)}
}

func (_c *MockQuerier_GetDocument_Call) Run(run func(ctx context.Context, id int)) *MockQuerier_GetDocument_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_GetDocument_Call) Return(document *Document, err error) *MockQuerier_GetDocument_Call {
	_c.Call.Return(document, err)
	return _c
}

func (_c *MockQuerier_GetDocument_Call) RunAndReturn(run func(ctx context.Context, id int) (*Document, error)) *MockQuerier_GetDocument_Call {
	_c.Call.Return(run)
	return _c
}

// GetDocumentEmbeddingsPage provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetDocumentEmbeddingsPage(ctx context.Context, limit int, offset int) ([]DocumentWithEmbedding, error) {
	ret := _mock.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetDocumentEmbeddingsPage")
	}

	var r0 []DocumentWithEmbedding
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) ([]DocumentWithEmbedding, error)); ok {
		return returnFunc(ctx, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) []DocumentWithEmbedding); ok {
		r0 = returnFunc(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]DocumentWithEmbedding)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = returnFunc(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetDocumentEmbeddingsPage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDocumentEmbeddingsPage'
type MockQuerier_GetDocumentEmbeddingsPage_Call struct {
	*mock.Call
}

// GetDocumentEmbeddingsPage is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *MockQuerier_Expecter) GetDocumentEmbeddingsPage(ctx interface{}, limit interface{}, offset interface{}) *MockQuerier_GetDocumentEmbeddingsPage_Call {
	return &MockQuerier_GetDocumentEmbeddingsPage_Call{Call: _e.mock.On("GetDocumentEmbeddingsPage", ctx, limit, offset)}
}

func (_c *MockQuerier_GetDocumentEmbeddingsPage_Call) Run(run func(ctx context.Context, limit int, offset int)) *MockQuerier_GetDocumentEmbeddingsPage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockQuerier_GetDocumentEmbeddingsPage_Call) Return(documentWithEmbeddings []DocumentWithEmbedding, err error) *MockQuerier_GetDocumentEmbeddingsPage_Call {
	_c.Call.Return(documentWithEmbeddings, err)
	return _c
}

func (_c *MockQuerier_GetDocumentEmbeddingsPage_Call) RunAndReturn(run func(ctx context.Context, limit int, offset int) ([]DocumentWithEmbedding, error)) *MockQuerier_GetDocumentEmbeddingsPage_Call {
	_c.Call.Return(run)
	return _c
}

// GetDocumentWithEmbedding provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetDocumentWithEmbedding(ctx context.Context, id int) (*DocumentWithEmbedding, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetDocumentWithEmbedding")
	}

	var r0 *DocumentWithEmbedding
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*DocumentWithEmbedding, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *DocumentWithEmbedding); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*DocumentWithEmbedding)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetDocumentWithEmbedding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDocumentWithEmbedding'
type MockQuerier_GetDocumentWithEmbedding_Call struct {
	*mock.Call
}

// GetDocumentWithEmbedding is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockQuerier_Expecter) GetDocumentWithEmbedding(ctx interface{}, id interface{}) *MockQuerier_GetDocumentWithEmbedding_Call {
	return &MockQuerier_GetDocumentWithEmbedding_Call{Call: _e.mock.On("GetDocumentWithEmbedding", ctx, id)}
}

func (_c *MockQuerier_GetDocumentWithEmbedding_Call) Run(run func(ctx context.Context, id int)) *MockQuerier_GetDocumentWithEmbedding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_GetDocumentWithEmbedding_Call) Return(documentWithEmbedding *DocumentWithEmbedding, err error) *MockQuerier_GetDocumentWithEmbedding_Call {
	_c.Call.Return(documentWithEmbedding, err)
	return _c
}

func (_c *MockQuerier_GetDocumentWithEmbedding_Call) RunAndReturn(run func(ctx context.Context, id int) (*DocumentWithEmbedding, error)) *MockQuerier_GetDocumentWithEmbedding_Call {
	_c.Call.Return(run)
	return _c
}

// GetEmbeddingsForDocument provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetEmbeddingsForDocument(ctx context.Context, documentId int) ([]Embedding, error) {
	ret := _mock.Called(ctx, documentId)

	if len(ret) == 0 {
		panic("no return value specified for GetEmbeddingsForDocument")
	}

	var r0 []Embedding
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]Embedding, error)); ok {
		return returnFunc(ctx, documentId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []Embedding); ok {
		r0 = returnFunc(ctx, documentId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Embedding)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, documentId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetEmbeddingsForDocument_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEmbeddingsForDocument'
type MockQuerier_GetEmbeddingsForDocument_Call struct {
	*mock.Call
}

// GetEmbeddingsForDocument is a helper method to define mock.On call
//   - ctx context.Context
//   - documentId int
func (_e *MockQuerier_Expecter) GetEmbeddingsForDocument(ctx interface{}, documentId interface{}) *MockQuerier_GetEmbeddingsForDocument_Call {
	return &MockQuerier_GetEmbeddingsForDocument_Call{Call: _e.mock.On("GetEmbeddingsForDocument", ctx, documentId)}
}

func (_c *MockQuerier_GetEmbeddingsForDocument_Call) Run(run func(ctx context.Context, documentId int)) *MockQuerier_GetEmbeddingsForDocument_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_GetEmbeddingsForDocument_Call) Return(embeddings []Embedding, err error) *MockQuerier_GetEmbeddingsForDocument_Call {
	_c.Call.Return(embeddings, err)
	return _c
}

func (_c *MockQuerier_GetEmbeddingsForDocument_Call) RunAndReturn(run func(ctx context.Context, documentId int) ([]Embedding, error)) *MockQuerier_GetEmbeddingsForDocument_Call {
	_c.Call.Return(run)
	return _c
}

// GetParentDocument provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetParentDocument(ctx context.Context, id int) (*Document, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetParentDocument")
	}

	var r0 *Document
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*Document, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *Document); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Document)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetParentDocument_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetParentDocument'
type MockQuerier_GetParentDocument_Call struct {
	*mock.Call
}

// GetParentDocument is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockQuerier_Expecter) GetParentDocument(ctx interface{}, id interface{}) *MockQuerier_GetParentDocument_Call {
	return &MockQuerier_GetParentDocument_Call{Call: _e.mock.On("GetParentDocument", ctx, id)}
}

func (_c *MockQuerier_GetParentDocument_Call) Run(run func(ctx context.Context, id int)) *MockQuerier_GetParentDocument_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_GetParentDocument_Call) Return(document *Document, err error) *MockQuerier_GetParentDocument_Call {
	_c.Call.Return(document, err)
	return _c
}

func (_c *MockQuerier_GetParentDocument_Call) RunAndReturn(run func(ctx context.Context, id int) (*Document, error)) *MockQuerier_GetParentDocument_Call {
	_c.Call.Return(run)
	return _c
}

// InsertDocument provides a mock function for the type MockQuerier
func (_mock *MockQuerier) InsertDocument(ctx context.Context, document Document, embedding Embedding) (int64, error) {
	ret := _mock.Called(ctx, document, embedding)

	if len(ret) == 0 {
		panic("no return value specified for InsertDocument")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, Document, Embedding) (int64, error)); ok {
		return returnFunc(ctx, document, embedding)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, Document, Embedding) int64); ok {
		r0 = returnFunc(ctx, document, embedding)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, Document, Embedding) error); ok {
		r1 = returnFunc(ctx, document, embedding)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_InsertDocument_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertDocument'
type MockQuerier_InsertDocument_Call struct {
	*mock.Call
}

// InsertDocument is a helper method to define mock.On call
//   - ctx context.Context
//   - document Document
//   - embedding Embedding
func (_e *MockQuerier_Expecter) InsertDocument(ctx interface{}, document interface{}, embedding interface{}) *MockQuerier_InsertDocument_Call {
	return &MockQuerier_InsertDocument_Call{Call: _e.mock.On("InsertDocument", ctx, document, embedding)}
}

func (_c *MockQuerier_InsertDocument_Call) Run(run func(ctx context.Context, document Document, embedding Embedding)) *MockQuerier_InsertDocument_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 Document
		if args[1] != nil {
			arg1 = args[1].(Document)
		}
		var arg2 Embedding
		if args[2] != nil {
			arg2 = args[2].(Embedding)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockQuerier_InsertDocument_Call) Return(n int64, err error) *MockQuerier_InsertDocument_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockQuerier_InsertDocument_Call) RunAndReturn(run func(ctx context.Context, document Document, embedding Embedding) (int64, error)) *MockQuerier_InsertDocument_Call {
	_c.Call.Return(run)
	return _c
}

// SearchSimilarEmbeddings provides a mock function for the type MockQuerier
func (_mock *MockQuerier) SearchSimilarEmbeddings(ctx context.Context, queryVector []float32, limit int) ([]DocumentWithEmbedding, error) {
	ret := _mock.Called(ctx, queryVector, limit)

	if len(ret) == 0 {
		panic("no return value specified for SearchSimilarEmbeddings")
	}

	var r0 []DocumentWithEmbedding
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []float32, int) ([]DocumentWithEmbedding, error)); ok {
		return returnFunc(ctx, queryVector, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []float32, int) []DocumentWithEmbedding); ok {
		r0 = returnFunc(ctx, queryVector, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]DocumentWithEmbedding)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []float32, int) error); ok {
		r1 = returnFunc(ctx, queryVector, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_SearchSimilarEmbeddings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchSimilarEmbeddings'
type MockQuerier_SearchSimilarEmbeddings_Call struct {
	*mock.Call
}

// SearchSimilarEmbeddings is a helper method to define mock.On call
//   - ctx context.Context
//   - queryVector []float32
//   - limit int
func (_e *MockQuerier_Expecter) SearchSimilarEmbeddings(ctx interface{}, queryVector interface{}, limit interface{}) *MockQuerier_SearchSimilarEmbeddings_Call {
	return &MockQuerier_SearchSimilarEmbeddings_Call{Call: _e.mock.On("SearchSimilarEmbeddings", ctx, queryVector, limit)}
}

func (_c *MockQuerier_SearchSimilarEmbeddings_Call) Run(run func(ctx context.Context, queryVector []float32, limit int)) *MockQuerier_SearchSimilarEmbeddings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []float32
		if args[1] != nil {
			arg1 = args[1].([]float32)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockQuerier_SearchSimilarEmbeddings_Call) Return(documentWithEmbeddings []DocumentWithEmbedding, err error) *MockQuerier_SearchSimilarEmbeddings_Call {
	_c.Call.Return(documentWithEmbeddings, err)
	return _c
}

func (_c *MockQuerier_SearchSimilarEmbeddings_Call) RunAndReturn(run func(ctx context.Context, queryVector []float32, limit int) ([]DocumentWithEmbedding, error)) *MockQuerier_SearchSimilarEmbeddings_Call {
	_c.Call.Return(run)
	return _c
}
