// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package datastore

type Document struct {
	ID       int64
	Document *string
}

type Embedding struct {
	Rowid      int64
	DocumentID int64
	Embedding  []byte
	Distance   float64
}
