// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package datastore

import (
	"context"
)

type Querier interface {
	GetDocument(ctx context.Context, id int64) (Document, error)
	GetEmbeddingWithDocument(ctx context.Context, rowid int64) (GetEmbeddingWithDocumentRow, error)
	InsertDocument(ctx context.Context, document *string) (Document, error)
	InsertEmbedding(ctx context.Context, embedding []byte) (int64, error)
	ListDocuments(ctx context.Context) ([]Document, error)
	SearchEmbedding(ctx context.Context, arg SearchEmbeddingParams) ([]SearchEmbeddingRow, error)
}

var _ Querier = (*Queries)(nil)
