// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package datastore

import (
	"context"
)

const getDocument = `-- name: GetDocument :one
SELECT id, document FROM document
WHERE id = ? LIMIT 1
`

func (q *Queries) GetDocument(ctx context.Context, id int64) (Document, error) {
	row := q.db.QueryRowContext(ctx, getDocument, id)
	var i Document
	err := row.Scan(&i.ID, &i.Document)
	return i, err
}

const getEmbeddingWithDocument = `-- name: GetEmbeddingWithDocument :one
SELECT e.rowid, e.embedding, e.document_id, d.document
FROM embeddings e
JOIN embeddings ON e.rowid = em.rowid
JOIN document d ON e.document_id = d.id
WHERE e.rowid = ? LIMIT 1
`

type GetEmbeddingWithDocumentRow struct {
	Rowid      int64
	Embedding  []byte
	DocumentID int64
	Document   *string
}

func (q *Queries) GetEmbeddingWithDocument(ctx context.Context, rowid int64) (GetEmbeddingWithDocumentRow, error) {
	row := q.db.QueryRowContext(ctx, getEmbeddingWithDocument, rowid)
	var i GetEmbeddingWithDocumentRow
	err := row.Scan(
		&i.Rowid,
		&i.Embedding,
		&i.DocumentID,
		&i.Document,
	)
	return i, err
}

const insertDocument = `-- name: InsertDocument :one
INSERT INTO document (
  document
) VALUES (
  ?
)
RETURNING id, document
`

func (q *Queries) InsertDocument(ctx context.Context, document *string) (Document, error) {
	row := q.db.QueryRowContext(ctx, insertDocument, document)
	var i Document
	err := row.Scan(&i.ID, &i.Document)
	return i, err
}

const insertEmbedding = `-- name: InsertEmbedding :one
INSERT INTO embeddings (
  embedding
) VALUES (
  ?
)
RETURNING rowid
`

func (q *Queries) InsertEmbedding(ctx context.Context, embedding []byte) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertEmbedding, embedding)
	var rowid int64
	err := row.Scan(&rowid)
	return rowid, err
}

const listDocuments = `-- name: ListDocuments :many
SELECT id, document FROM document
ORDER BY id
`

func (q *Queries) ListDocuments(ctx context.Context) ([]Document, error) {
	rows, err := q.db.QueryContext(ctx, listDocuments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(&i.ID, &i.Document); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchEmbedding = `-- name: SearchEmbedding :many
SELECT 
  rowid,
  distance
FROM embeddings
WHERE embedding MATCH ?
ORDER BY distance
LIMIT ?
`

type SearchEmbeddingParams struct {
	Embedding []byte
	Limit     int64
}

type SearchEmbeddingRow struct {
	Rowid    int64
	Distance float64
}

func (q *Queries) SearchEmbedding(ctx context.Context, arg SearchEmbeddingParams) ([]SearchEmbeddingRow, error) {
	rows, err := q.db.QueryContext(ctx, searchEmbedding, arg.Embedding, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchEmbeddingRow
	for rows.Next() {
		var i SearchEmbeddingRow
		if err := rows.Scan(&i.Rowid, &i.Distance); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
