// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package datastore

import (
	"context"
)

type Querier interface {
	CheckVersion(ctx context.Context) (interface{}, error)
	GetChunk(ctx context.Context, id int64) (Chunk, error)
}

var _ Querier = (*Queries)(nil)
