// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package datastore

import (
	"context"
)

const checkVersion = `-- name: CheckVersion :one
SELECT vec_version()
`

func (q *Queries) CheckVersion(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, checkVersion)
	var vec_version interface{}
	err := row.Scan(&vec_version)
	return vec_version, err
}

const getChunk = `-- name: GetChunk :one
SELECT id, chunk FROM chunks
WHERE id = ? LIMIT 1
`

func (q *Queries) GetChunk(ctx context.Context, id int64) (Chunk, error) {
	row := q.db.QueryRowContext(ctx, getChunk, id)
	var i Chunk
	err := row.Scan(&i.ID, &i.Chunk)
	return i, err
}
