// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package stages

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockStage creates a new instance of MockStage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStage[IN any, OUT any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStage[IN, OUT] {
	mock := &MockStage[IN, OUT]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStage is an autogenerated mock type for the Stage type
type MockStage[IN any, OUT any] struct {
	mock.Mock
}

type MockStage_Expecter[IN any, OUT any] struct {
	mock *mock.Mock
}

func (_m *MockStage[IN, OUT]) EXPECT() *MockStage_Expecter[IN, OUT] {
	return &MockStage_Expecter[IN, OUT]{mock: &_m.Mock}
}

// Run provides a mock function for the type MockStage
func (_mock *MockStage[IN, OUT]) Run(ctx context.Context, in <-chan IN) <-chan OUT {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 <-chan OUT
	if returnFunc, ok := ret.Get(0).(func(context.Context, <-chan IN) <-chan OUT); ok {
		r0 = returnFunc(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan OUT)
		}
	}
	return r0
}

// MockStage_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockStage_Run_Call[IN any, OUT any] struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - in <-chan IN
func (_e *MockStage_Expecter[IN, OUT]) Run(ctx interface{}, in interface{}) *MockStage_Run_Call[IN, OUT] {
	return &MockStage_Run_Call[IN, OUT]{Call: _e.mock.On("Run", ctx, in)}
}

func (_c *MockStage_Run_Call[IN, OUT]) Run(run func(ctx context.Context, in <-chan IN)) *MockStage_Run_Call[IN, OUT] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 <-chan IN
		if args[1] != nil {
			arg1 = args[1].(<-chan IN)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStage_Run_Call[IN, OUT]) Return(vCh <-chan OUT) *MockStage_Run_Call[IN, OUT] {
	_c.Call.Return(vCh)
	return _c
}

func (_c *MockStage_Run_Call[IN, OUT]) RunAndReturn(run func(ctx context.Context, in <-chan IN) <-chan OUT) *MockStage_Run_Call[IN, OUT] {
	_c.Call.Return(run)
	return _c
}
