// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ai

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockEmbeddingModel creates a new instance of MockEmbeddingModel. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEmbeddingModel(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEmbeddingModel {
	mock := &MockEmbeddingModel{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEmbeddingModel is an autogenerated mock type for the EmbeddingModel type
type MockEmbeddingModel struct {
	mock.Mock
}

type MockEmbeddingModel_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEmbeddingModel) EXPECT() *MockEmbeddingModel_Expecter {
	return &MockEmbeddingModel_Expecter{mock: &_m.Mock}
}

// GenerateEmbedding provides a mock function for the type MockEmbeddingModel
func (_mock *MockEmbeddingModel) GenerateEmbedding(ctx context.Context, text string) ([]float32, error) {
	ret := _mock.Called(ctx, text)

	if len(ret) == 0 {
		panic("no return value specified for GenerateEmbedding")
	}

	var r0 []float32
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]float32, error)); ok {
		return returnFunc(ctx, text)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []float32); ok {
		r0 = returnFunc(ctx, text)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]float32)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, text)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEmbeddingModel_GenerateEmbedding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateEmbedding'
type MockEmbeddingModel_GenerateEmbedding_Call struct {
	*mock.Call
}

// GenerateEmbedding is a helper method to define mock.On call
//   - ctx context.Context
//   - text string
func (_e *MockEmbeddingModel_Expecter) GenerateEmbedding(ctx interface{}, text interface{}) *MockEmbeddingModel_GenerateEmbedding_Call {
	return &MockEmbeddingModel_GenerateEmbedding_Call{Call: _e.mock.On("GenerateEmbedding", ctx, text)}
}

func (_c *MockEmbeddingModel_GenerateEmbedding_Call) Run(run func(ctx context.Context, text string)) *MockEmbeddingModel_GenerateEmbedding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEmbeddingModel_GenerateEmbedding_Call) Return(float32s []float32, err error) *MockEmbeddingModel_GenerateEmbedding_Call {
	_c.Call.Return(float32s, err)
	return _c
}

func (_c *MockEmbeddingModel_GenerateEmbedding_Call) RunAndReturn(run func(ctx context.Context, text string) ([]float32, error)) *MockEmbeddingModel_GenerateEmbedding_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateEmbeddings provides a mock function for the type MockEmbeddingModel
func (_mock *MockEmbeddingModel) GenerateEmbeddings(ctx context.Context, text []string) ([][]float32, error) {
	ret := _mock.Called(ctx, text)

	if len(ret) == 0 {
		panic("no return value specified for GenerateEmbeddings")
	}

	var r0 [][]float32
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) ([][]float32, error)); ok {
		return returnFunc(ctx, text)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) [][]float32); ok {
		r0 = returnFunc(ctx, text)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]float32)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = returnFunc(ctx, text)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEmbeddingModel_GenerateEmbeddings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateEmbeddings'
type MockEmbeddingModel_GenerateEmbeddings_Call struct {
	*mock.Call
}

// GenerateEmbeddings is a helper method to define mock.On call
//   - ctx context.Context
//   - text []string
func (_e *MockEmbeddingModel_Expecter) GenerateEmbeddings(ctx interface{}, text interface{}) *MockEmbeddingModel_GenerateEmbeddings_Call {
	return &MockEmbeddingModel_GenerateEmbeddings_Call{Call: _e.mock.On("GenerateEmbeddings", ctx, text)}
}

func (_c *MockEmbeddingModel_GenerateEmbeddings_Call) Run(run func(ctx context.Context, text []string)) *MockEmbeddingModel_GenerateEmbeddings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEmbeddingModel_GenerateEmbeddings_Call) Return(float32ss [][]float32, err error) *MockEmbeddingModel_GenerateEmbeddings_Call {
	_c.Call.Return(float32ss, err)
	return _c
}

func (_c *MockEmbeddingModel_GenerateEmbeddings_Call) RunAndReturn(run func(ctx context.Context, text []string) ([][]float32, error)) *MockEmbeddingModel_GenerateEmbeddings_Call {
	_c.Call.Return(run)
	return _c
}

// ModelId provides a mock function for the type MockEmbeddingModel
func (_mock *MockEmbeddingModel) ModelId() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ModelId")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockEmbeddingModel_ModelId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ModelId'
type MockEmbeddingModel_ModelId_Call struct {
	*mock.Call
}

// ModelId is a helper method to define mock.On call
func (_e *MockEmbeddingModel_Expecter) ModelId() *MockEmbeddingModel_ModelId_Call {
	return &MockEmbeddingModel_ModelId_Call{Call: _e.mock.On("ModelId")}
}

func (_c *MockEmbeddingModel_ModelId_Call) Run(run func()) *MockEmbeddingModel_ModelId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEmbeddingModel_ModelId_Call) Return(s string) *MockEmbeddingModel_ModelId_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockEmbeddingModel_ModelId_Call) RunAndReturn(run func() string) *MockEmbeddingModel_ModelId_Call {
	_c.Call.Return(run)
	return _c
}
