// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package store

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockDatastore creates a new instance of MockDatastore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDatastore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDatastore {
	mock := &MockDatastore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDatastore is an autogenerated mock type for the Datastore type
type MockDatastore struct {
	mock.Mock
}

type MockDatastore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDatastore) EXPECT() *MockDatastore_Expecter {
	return &MockDatastore_Expecter{mock: &_m.Mock}
}

// Initialize provides a mock function for the type MockDatastore
func (_mock *MockDatastore) Initialize(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Initialize")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDatastore_Initialize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Initialize'
type MockDatastore_Initialize_Call struct {
	*mock.Call
}

// Initialize is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDatastore_Expecter) Initialize(ctx interface{}) *MockDatastore_Initialize_Call {
	return &MockDatastore_Initialize_Call{Call: _e.mock.On("Initialize", ctx)}
}

func (_c *MockDatastore_Initialize_Call) Run(run func(ctx context.Context)) *MockDatastore_Initialize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDatastore_Initialize_Call) Return(err error) *MockDatastore_Initialize_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDatastore_Initialize_Call) RunAndReturn(run func(ctx context.Context) error) *MockDatastore_Initialize_Call {
	_c.Call.Return(run)
	return _c
}

// InsertChunks provides a mock function for the type MockDatastore
func (_mock *MockDatastore) InsertChunks(ctx context.Context, chunks []Chunk) (int, error) {
	ret := _mock.Called(ctx, chunks)

	if len(ret) == 0 {
		panic("no return value specified for InsertChunks")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []Chunk) (int, error)); ok {
		return returnFunc(ctx, chunks)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []Chunk) int); ok {
		r0 = returnFunc(ctx, chunks)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []Chunk) error); ok {
		r1 = returnFunc(ctx, chunks)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDatastore_InsertChunks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertChunks'
type MockDatastore_InsertChunks_Call struct {
	*mock.Call
}

// InsertChunks is a helper method to define mock.On call
//   - ctx context.Context
//   - chunks []Chunk
func (_e *MockDatastore_Expecter) InsertChunks(ctx interface{}, chunks interface{}) *MockDatastore_InsertChunks_Call {
	return &MockDatastore_InsertChunks_Call{Call: _e.mock.On("InsertChunks", ctx, chunks)}
}

func (_c *MockDatastore_InsertChunks_Call) Run(run func(ctx context.Context, chunks []Chunk)) *MockDatastore_InsertChunks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []Chunk
		if args[1] != nil {
			arg1 = args[1].([]Chunk)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDatastore_InsertChunks_Call) Return(n int, err error) *MockDatastore_InsertChunks_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockDatastore_InsertChunks_Call) RunAndReturn(run func(ctx context.Context, chunks []Chunk) (int, error)) *MockDatastore_InsertChunks_Call {
	_c.Call.Return(run)
	return _c
}

// SearchIndex provides a mock function for the type MockDatastore
func (_mock *MockDatastore) SearchIndex(ctx context.Context, searchToken []float32) ([]SearchResult, error) {
	ret := _mock.Called(ctx, searchToken)

	if len(ret) == 0 {
		panic("no return value specified for SearchIndex")
	}

	var r0 []SearchResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []float32) ([]SearchResult, error)); ok {
		return returnFunc(ctx, searchToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []float32) []SearchResult); ok {
		r0 = returnFunc(ctx, searchToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]SearchResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []float32) error); ok {
		r1 = returnFunc(ctx, searchToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDatastore_SearchIndex_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchIndex'
type MockDatastore_SearchIndex_Call struct {
	*mock.Call
}

// SearchIndex is a helper method to define mock.On call
//   - ctx context.Context
//   - searchToken []float32
func (_e *MockDatastore_Expecter) SearchIndex(ctx interface{}, searchToken interface{}) *MockDatastore_SearchIndex_Call {
	return &MockDatastore_SearchIndex_Call{Call: _e.mock.On("SearchIndex", ctx, searchToken)}
}

func (_c *MockDatastore_SearchIndex_Call) Run(run func(ctx context.Context, searchToken []float32)) *MockDatastore_SearchIndex_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []float32
		if args[1] != nil {
			arg1 = args[1].([]float32)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDatastore_SearchIndex_Call) Return(searchResults []SearchResult, err error) *MockDatastore_SearchIndex_Call {
	_c.Call.Return(searchResults, err)
	return _c
}

func (_c *MockDatastore_SearchIndex_Call) RunAndReturn(run func(ctx context.Context, searchToken []float32) ([]SearchResult, error)) *MockDatastore_SearchIndex_Call {
	_c.Call.Return(run)
	return _c
}
