name: release
on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - uses: actions/setup-go@v6
      with:
        go-version-file: go.mod

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - uses: mlugg/setup-zig@v2

    - name: Download macOS SDK
      run: |
        curl -L https://github.com/joseluisq/macosx-sdks/releases/download/13.3/MacOSX13.3.sdk.tar.xz -o sdk.tar.xz
        tar -xf sdk.tar.xz
        echo "SDK_PATH=$PWD/MacOSX13.3.sdk" >> $GITHUB_ENV

    - uses: goreleaser/goreleaser-action@v7
      with:
        version: latest
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}

